### ISSUE TITLE
about cleos commit 21eea787737176998831d106dda0257aa53976f9

### ISSUE THREAD

**Issue by fingera** [eosforce/eosforce#12]
1. 支持了EOS转账但破坏了代币转账
2. 在eosio.token里创建一个名字为EOS的token就是为了 eosio里的真实EOS方便过来查资料？ 不如cleos直接写死哦，本身EOS精度都是固定的 eosio::chain::EOS_SYMBOL。

我那个pr没有这些问题的啊

**Comment by yzuyhp** [comment]
1、已修改， 代币转账时 加  -c eosio.token
2、 增加 EOS 的好处很多， 以后可以查询 EOS 的资料信息，比如当前 EOS 总量等

**Comment by fingera** [comment]
好吧，那还要改合约 把总量信息更新到 eosio.token 里
