### ISSUE TITLE
帐户少于0.03, 领取分红失败

### ISSUE THREAD

**Issue by cjy37** [eosforce/eosforce#4]
详见： [https://github.com/eosforce/wallet-desktop/issues/81](https://github.com/eosforce/wallet-desktop/issues/81)

目前不能充值，感觉只能等死

@eosforce @fiser321 @bookcool

**Comment by ShuhanSun** [comment]
最新版钱包已经加上了余额过少的提醒。可以从另一个账户转给此账户一些eos即可。

**Comment by cjy37** [comment]
@bookcool 没有另一个帐号，给我转一点救济一下，用户名：
```
ha4temjrgqge
```

**Comment by fanyang1988** [comment]
no fee is changed
